/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.minutestoseconds.johnathan;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public double minutesToSeconds(double minutes) {
        return minutes * 60;
    }

    public static void main(String[] args) {
        
    }
}
