/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.minutestoseconds.johnathan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test void minutesToSeconds() {
        App classUnderTest = new App();
        double minutes;
        minutes = 1;
        assertEquals(classUnderTest.minutesToSeconds(minutes), 60);
    }
}
